### ISSUE TITLE
Caching, disabling and re-enabling subsets

### ISSUE THREAD

**Issue by bendulum** [p3drosola/Backbone.VirtualCollection#61]
I'm playing around with this plugin at the moment, it has been very useful so far. I have created a wrapper object that creates my subsets, comparators and filter functions dynamically and caches them.

In my system I'm creating many subsets over time. I'm trying to achieve the following:

- create subset for current view
- cache subset somewhere globally
- when the view is closed, "disable" the subset (stopListening)
- when view is opened again, get the subset from cache, "enable" and refresh it

Right now the plugin has no interface for that. I would have to manually call:
- stopListening to disable
- bind all events again manually and call _rebuildIndex to enable

.. or something along those lines.

Would such an implementation make sense, or would the increase in performance be marginal?

**Comment by masylum** [comment]
I would keep `VirtualCollection` as simple as it is. You could add a layer on top to achieve that

**Comment by p3drosola** [comment]
I don't think there's really any performance benefits to be obtained by "pausing" the virtualcollection. [Instanciation](https://github.com/p3drosola/Backbone.VirtualCollection/blob/master/backbone.virtual-collection.js#L10) is basically just rebuilding the index.

But like @masylum said, if that's the approach you want to go with, a helper function will get the job done, but doesn't really belong in virtaulcollection.
