### ISSUE TITLE
Properly override clone

### ISSUE THREAD

**Issue by wilfriedvanasten** [p3drosola/Backbone.VirtualCollection#68]
Currently VirtualCollection does not override Backbone.Collection.clone. This breaks clients using that function since the default implementation passes this.models to this.constructor instead of this.collection. This causes an undefined function error in _rebuildIndex since array does not have each.

I have been working on an implementation, but am unsure how to preserve the filter (The backbone collection spec just says that the resulting collection will have the same models, but I think for VirtualCollection the behaviour should be the same too). Initially I made a copy of the options hash and stored it on this. However this backbone issue https://github.com/jashkenas/backbone/issues/3013 made me rethink that solution. So now I just try to pass the bare essentials (the collection, the comparator and the filter) to get correct behaviour for a vanilla virtual collection, but I can't access the filter passed to the constructor anymore. Should I preserve the filter as a property and then pass it on in the options? Or should I set accepts to this.accepts and then call _rebuildIndex ? Or is there another even better option?

**Comment by p3drosola** [comment]
That's a good question @wilfriedvanasten. It brings to light the fact that I didn't really design this with inheritance in mind. Like you mentioned, cloning with all the options can have unintended side effects (in particular you lose control over the close_with option).

Can you tell me a little more about your usecase? What are you trying to achieve?

**Comment by wilfriedvanasten** [comment]
Well the mentioned issue actually arose from using a BackGrid Extension for filtering that relied on clone to provide a cloned collection to do the filtering on. I now realize that my proposed implementation would actually result in disaster since the extension would likely use the clone to either 1) maintain the original collection or 2) to represent the filtered contents. Since it would be modifying the collection using virtual collection in either case would result in modification to the underlying collection which is totally wrong. So I will not use that extension and instead write something that works with virtual collection's filtering capabilities instead.

It does however show an interesting apparently expected behaviour of clone: That the resulting collection be completely independent of the original collection. By being bound to the underlying collection this would be hard for a "natural clone" of a virtual collection to provide. So in that sense the best approximation would actually be for clone to return a new Backbone.Collection based on the virtual collections models instead. However than the filtering behaviour would not be maintained which someone who calls VirtualCollection.clone might expect. This issue is more hairy then I initially thought.

**Comment by p3drosola** [comment]
Yep, I get your point.

I think what would make most sense is to return a Backbone.Collection and be done with it. If what you want is a dynamic virtual collection with the same filter, we'll leave it up to the user. Because you'll need to manage the listener lifespan as well, etc. It's really not complicated, but it varies depending on your implementation.

I think it's just a matter of changing `return new this.constructor`  for `return new this.collection.constructor`. But if you make a PR with tests I'll be happy to merge it.

**Comment by p3drosola** [comment]
Ok, I'm not sure this is terribly useful, but I added support for clone. At least it doesn't throw an error.

**Comment by p3drosola** [comment]
https://github.com/p3drosola/Backbone.VirtualCollection/commit/2e5e2fd1054f057370f13b3d188b1ca151fecd31
