### ISSUE TITLE
Problem with Sort when not overridden

### ISSUE THREAD

**Issue by tkwidmer** [p3drosola/Backbone.VirtualCollection#69]
Had an error in the console when attempting to sort the virtual collection. Looks like it didn't properly get the comparator from the original collection. I'm trying to return a filtered set of accounts with an association to the goal. Pretty standard stuff. 

```coffeescript
class Collections.AccountsCollection extends Backbone.Collection

  comparator: (m) ->
    return -Date.parse(m.get('updatedAt'))

  belongToGoal: (id) ->
    new ViritualCollection(@, {filter: {goalId: id}})

```

and the code that caused the error. Dashboard.goal is the goal that the accounts are associated to.

```coffeescript
Dashboard.accounts = new Collections.AccountsCollection(jsonResponse)
@accounts = Dashboard.accounts.belongToGoal(Dashboard.goal.get('id'))
@updatedAt = moment(@accounts.sort().pluck('updatedAt')[0]).fromNow()
```

my current work around is just passing in the defined comparator to the virtual collection on init. This makes the sort happen correctly.

```coffeescript
belongToGoal: (id) ->
  new VirtualCollection(@, {filter:{goalId: id}, comparator: @comparator})
```

**Comment by disruptek** [comment]
You have one (or -1) too many parenthesis in your `comparator()` but maybe it's a transcription error.

You shouldn't need your workaround, and obviously, it has performance ramifications.  Can you confirm that the code really isn't working correctly?  Which version of VirtualCollection are you using?

**Comment by tkwidmer** [comment]
I pulled down the most recent version of ViritualCollection because I had just stumbled upon it this week. @disruptek.

The missing paren was a transcription error, it's correct in my code.

**Comment by disruptek** [comment]
Can you confirm that the VirtualCollection is truly unsorted?  Does the behavior change when you set the comparator to `null`?

**Comment by tkwidmer** [comment]
Let me try it again as soon as I get back up and developing this morning and I'll comment again.

**Comment by p3drosola** [comment]
@disruptek is right on all points. It's not necessary, and it makes it slower.

I've just added an [explicit test case](https://github.com/p3drosola/Backbone.VirtualCollection/commit/207ac21935f800d72a76c89abd91d64ba16e728c) for this, and it's passing properly.

**Comment by p3drosola** [comment]
I just noticed the problem.

in your snippet you're calling `sort` on the virtual collection. it's not necessary because (as the test above illustrates) vc's "inherit" the order of the parent collection unless they have their own comparator.

The error you're seeing actually comes from Backbone, not VirtualCollection. It's complains  when you ask it to sort a collection that doesn't have  a comparator. Hope that helps.

**Comment by tkwidmer** [comment]
hrm. I guess the problem seemed that backbone's collection was not staying sorted by the comparator, I had to call .sort() on it for it to end up sorting correctly. -- I was misunderstanding the use of the word 'inherit.' sorry about that.
