### ISSUE TITLE
Backbone update event not being handled

### ISSUE THREAD

**Issue by RealAdamSinger** [p3drosola/Backbone.VirtualCollection#72]
as of backbone v1.2.0 — May 13, 2015, an "update" event is now triggered on a collection after models have been added/removed. Backbone.VirtualCollection currently does not support this

**Comment by p3drosola** [comment]
PRs welcome :)

**Comment by RealAdamSinger** [comment]
I'll see what i can do after i get my application running again, maybe in a few days

**Comment by megawac** [comment]
This is easy enough to support in the way it was implemented in BB@1.2 however may be trickier in BB1.3 as the changes are now tracked.

So whenever there are changes the following meta should be passed to listeners `{changes: {added: [...], removed: [...], merged: [...]}}`

It would be significantly easier to support `add`, `remove`, `change` events managed through the `update` event then the other way around, though that would force the version range to be `backbone: ^1.3`.

Thoughts?

**Comment by p3drosola** [comment]
hmm, yeah I wouldn't limit support to backbone > 1.3

**Comment by p3drosola** [comment]
https://github.com/p3drosola/Backbone.VirtualCollection/pull/91
