### ISSUE TITLE
Garbage Collection

### ISSUE THREAD

**Issue by dtodor** [p3drosola/Backbone.VirtualCollection#82]
It seems that the VirtualCollection instances will not be garbage collected, since for each accepted model an event listener is registered:
```
_rebuildIndex: function () {
...
    this.collection.each(function (model, i) {
      if (this.accepts(model, i)) {
        model.on('all', this._onAllEvent, this);
...
}
```
The event listener is however not deregistered inside the ```bindLifecycle``` method. I guess ```model.off(...)``` should be called when a destroy event is emitted, e.g.:
```
bindLifecycle: function (view, method_name) {
  view.on(method_name, _.bind(function() {
    this.stopListening();
    _.invoke(this.models, 'off', 'all', this._onAllEvent, this);
  }, this));
}
```
Any thoughts?

**Comment by mllocs** [comment]
You can bind the virtual collection with a view with the `close_with` attribute. Once the view is closed, the virtual collection will remove the listeners.

**Comment by p3drosola** [comment]
I think you're right @dtodor, although I think the solution would be to replace

`model.on('all', this._onAllEvent, this);` for `this.listenTo(model, 'all', this._onAllEvent)`

and https://github.com/p3drosola/Backbone.VirtualCollection/blob/master/src/backbone.virtual-collection.js#L41 for `_.each(this.models, function () { this.stopListening(model) }, this)`

would you agree?

**Comment by p3drosola** [comment]
would also need to update `_indexRemove` and `_onRemove`

**Comment by dtodor** [comment]
Yes, that would be the better solution.

**Comment by p3drosola** [comment]
nice. I'll try and get to it during a flight on saturday :)
