### ISSUE TITLE
Option for creating deaf collections

### ISSUE THREAD

**Issue by rogovdm** [p3drosola/Backbone.VirtualCollection#85]
Sometimes it's very convenient to create deaf virtual collections — one that does not `listenTo`parents events. The reason would be a perfomance tricks.

How about an option something like `listenTo: false` or `trackEvents: false`?

**Comment by p3drosola** [comment]
Why not just call stopListening() after creating the collection?

**Comment by rogovdm** [comment]
Nice.

I'll see if adding and removing a bunch of events at one time won't cause a perfomance issue.
