### ISSUE TITLE
Event "change:attr" is not handled in some cases

### ISSUE THREAD

**Issue by gregorybarale** [p3drosola/Backbone.VirtualCollection#92]
Hi,

I think there is an issue about the trigger of events like "change:attr".

Case 1: expected behavior
- You create a virtual collection from a collection populated with valid models by the filter function
- You change an attribute of one of those models,
- The event "change:attr" will be triggered by the virtual collection

Case 2: unexpected behavior
- You add a model that is not valid in the collection
- Make it valid, which will add it in the virtual collection
- Change some attribute
- The event "change:attr" will not be triggered by the virtual collection

My analysis:
If think the problem is when you add an element (with the "_onAdd" function), it will listen the "all" event to call the function "_onAllEvent" which make possible to trigger the "change:attr" event.
But if you add an invalid model and then make it valid, you will go through the "_onChange" function which will not listen to the "all" event.

Is it made on purpose? If not, when do you think you will be able to correct it?
Hope i'm clear enough.

**Comment by p3drosola** [comment]
Hi @gregorybarale, I think I understand what you're describing.

I can't make any promises about getting it fixed though.... pull requests are welcome.

**Comment by gregorybarale** [comment]
@p3drosola, thanks, i'll look at it and make a pull request.

**Comment by gregorybarale** [comment]
@p3drosola, i think i am ready to make my pull request, would you like me to generate the project or only add the source and test modification in my request?

**Comment by p3drosola** [comment]
either way is fine. running `gulp`  generates the compiled files

**Comment by gregorybarale** [comment]
Ok, i've made my pull request, i didn't generate the whole project and only commit the source and test modification

**Comment by p3drosola** [comment]
https://github.com/p3drosola/Backbone.VirtualCollection/pull/93
